### ISSUE TITLE
Broken features with Violentmonkey

### ISSUE THREAD

**Issue by throwaway-slut** [GoatSalad/megukascript#55]
Certain features are broken when the script is used with [Violentmonkey](https://violentmonkey.github.io) instead of Tampermonkey. I haven't tested everything, but at the very least image sekritposting and the music player are broken.

Error when using the music player:
```
[Violentmonkey][page][megucascript] 
ReferenceError: currentlyEnabledOptions is not defined
currentlyEnabledOptions is not defined

Line 1353, column 58:
  if (currentlyEnabledOptions.has("enablemegucaplayer")) mgcPl_setupPlaylist();
                                                         ^
```
Error when hovering over a picture with a sekritpost:
```
Uncaught TypeError: Cannot read property 'substring' of undefined
    at onload (<anonymous>:383:61)
    at <anonymous>:1:5796
    at d (<anonymous>:1:5841)
    at w (<anonymous>:1:15799)
    at HTMLDocument.<anonymous> (<anonymous>:1:4221)
```

Tested with both Opera and Waterfox. Features work fine using Tampermonkey with the same browsers.

**Comment by GoatSalad** [comment]
Monkey begone
